package dns

import (
	"bytes"
	"context"
	"encoding/binary"
	"io"
	"net"
	"testing"
	"time"

	"github.com/stretchr/testify/require"
)

func TestUpstreamsFromReader(t *testing.T) {
	input := stringsReader(`
# Generated by something on the host.
nameserver 127.0.0.53 # systemd-resolved stub
nameserver 2001:db8::53
nameserver 127.0.0.53
search ec2.internal
options ndots:2
`)

	got, err := UpstreamsFromReader(input)
	require.NoError(t, err)
	require.Equal(t, []string{
		"127.0.0.53:53",
		"[2001:db8::53]:53",
	}, got)
}

func TestNormalizeUpstreams(t *testing.T) {
	got := normalizeUpstreams([]string{
		" 127.0.0.53 ",
		"8.8.8.8:5353",
		"2001:db8::53",
		"",
	})
	require.Equal(t, []string{
		"127.0.0.53:53",
		"8.8.8.8:5353",
		"[2001:db8::53]:53",
	}, got)
}

func TestForwardUDP(t *testing.T) {
	ctx, cancel := context.WithCancel(t.Context())
	defer cancel()

	upstream := startUDPUpstream(t, []byte("response"))
	fwd, err := Start(ctx, Config{
		ListenAddr: "127.0.0.1:0",
		Upstreams:  []string{upstream},
	})
	require.NoError(t, err)
	defer func() { require.NoError(t, fwd.Close()) }()

	client, err := net.Dial("udp", fwd.UDPAddr().String())
	require.NoError(t, err)
	defer func() { require.NoError(t, client.Close()) }()
	require.NoError(t, client.SetDeadline(time.Now().Add(time.Second)))

	_, err = client.Write([]byte("query"))
	require.NoError(t, err)

	buf := make([]byte, maxDNSPacket)
	n, err := client.Read(buf)
	require.NoError(t, err)
	require.Equal(t, []byte("response"), buf[:n])
}

func TestForwardTCP(t *testing.T) {
	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()

	upstream := startTCPUpstream(t, []byte("response"))
	fwd, err := Start(ctx, Config{
		ListenAddr: "127.0.0.1:0",
		Upstreams:  []string{upstream},
	})
	require.NoError(t, err)
	defer func() { require.NoError(t, fwd.Close()) }()

	client, err := net.Dial("tcp", fwd.TCPAddr().String())
	require.NoError(t, err)
	defer func() { require.NoError(t, client.Close()) }()
	require.NoError(t, client.SetDeadline(time.Now().Add(time.Second)))

	_, err = client.Write(tcpMessage(t, []byte("query")))
	require.NoError(t, err)

	got, err := readTCPDNSMessage(client)
	require.NoError(t, err)
	require.Equal(t, tcpMessage(t, []byte("response")), got)
}

func startUDPUpstream(t *testing.T, response []byte) string {
	t.Helper()

	conn, err := net.ListenPacket("udp", "127.0.0.1:0")
	require.NoError(t, err)
	t.Cleanup(func() { require.NoError(t, conn.Close()) })

	go func() {
		buf := make([]byte, maxDNSPacket)
		_, addr, err := conn.ReadFrom(buf)
		if err != nil {
			return
		}
		_, err = conn.WriteTo(response, addr)
		require.NoError(t, err)
	}()
	return conn.LocalAddr().String()
}

func startTCPUpstream(t *testing.T, response []byte) string {
	t.Helper()

	ln, err := net.Listen("tcp", "127.0.0.1:0")
	require.NoError(t, err)
	t.Cleanup(func() { require.NoError(t, ln.Close()) })

	go func() {
		conn, err := ln.Accept()
		if err != nil {
			return
		}
		defer func() { require.NoError(t, conn.Close()) }()

		_, err = readTCPDNSMessage(conn)
		if err != nil {
			return
		}
		_, err = conn.Write(tcpMessage(t, response))
		require.NoError(t, err)
	}()
	return ln.Addr().String()
}

func tcpMessage(t *testing.T, msg []byte) []byte {
	var buf bytes.Buffer
	require.NoError(t, binary.Write(&buf, binary.BigEndian, uint16(len(msg))))
	_, err := buf.Write(msg)
	require.NoError(t, err)
	return buf.Bytes()
}

func stringsReader(s string) io.Reader {
	return bytes.NewBufferString(s)
}
