FROM golang:1.26

WORKDIR /app

RUN mkdir cmd/ internal/ vendor/
COPY cmd/ ./cmd/
COPY internal/ ./internal/
COPY vendor/ ./vendor/
COPY Makefile go.mod go.sum ./
COPY docker/run-unit-tests.sh ./run-unit-tests.sh
RUN chmod +x ./run-unit-tests.sh

RUN go mod download

CMD ["/app/run-unit-tests.sh"]
