FROM golang:1.23

WORKDIR /app

RUN mkdir cmd/ internal/ vendor/
COPY cmd/ ./cmd/
COPY internal/ ./internal/
COPY vendor/ ./vendor/
COPY Makefile go.mod go.sum ./
RUN cat > ./run-unit-tests.sh <<EOF
#!/usr/bin/env bash
cd /app
# Needed for Go's build cache.
export HOME=/app
# Needed because otherwise we're getting:
# fork/exec /tmp/go-build1885828642/b001/cmd.test: permission denied
mkdir -p /app/tmp
export TMPDIR=/app/tmp
echo "Running Go unit tests..."
$(which go) test -cover ./...
EOF

RUN go mod download

CMD ["/app/run-unit-tests.sh"]
