package enclave

import (
	"bytes"
	"crypto/sha512"
	"fmt"
	"sort"
	"strings"
)

var emptyPCR = make([]byte, sha512.Size384)

// PCR represents the enclave's platform configuration register (PCR) values.
type PCR map[uint][]byte

// FromDebugMode returns true if the given PCR map was generated by an enclave
// in debug mode.
func (p PCR) FromDebugMode() bool {
	// PCRs 0, 1, and 2 are set at compile time but will be unset if the enclave
	// is running in debug mode.
	return bytes.Equal(p[0], emptyPCR) &&
		bytes.Equal(p[1], emptyPCR) &&
		bytes.Equal(p[2], emptyPCR)
}

// String returns a human-readable representation of the PCR map.
func (p PCR) String() string {
	s := []string{}
	for key, val := range p {
		s = append(s, fmt.Sprintf("%d: %x\n", key, val))
	}
	sort.Strings(s)
	return strings.Join(s, "")
}

// Equal returns true if (and only if) the two given PCR maps are identical.
// Note that this function ignores PCR4 because it contains a hash over the
// parent's instance ID, which is only known at runtime. We ignore it for now.
func (ours PCR) Equal(theirs PCR) bool {
	if pcrLen(ours) != pcrLen(theirs) {
		return false
	}

	for i, ourValue := range ours {
		if i == 4 {
			continue
		}
		theirValue, exists := theirs[i]
		if !exists {
			return false
		}
		if !bytes.Equal(ourValue, theirValue) {
			return false
		}
	}
	return true
}

func pcrLen(p PCR) int {
	n := len(p)
	if _, ok := p[4]; ok {
		n--
	}
	return n
}
